# Site settings
title: Boram Kim
email: boram.kim1@lehman.cuny.edu
description: "Boram Kim"
keywords: "jekyll, theme, web development, responsive, bootstrap"
skills: "Assistant Professor at CUNY Lehman College"
meta_author: Kim Boram

# formspree endpoint
formspree: myyrzavn

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:


contact: static


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 68b2e3
  primary-rgb: "128, 204, 255"
  secondary: 137a63
  secondary-dark: 146b85

# Footer settings
footer:
  copyright: Boram Kim
  location: Location
  social: Social
  extra: Affiliations

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://google.com
  - title: instagram
    url: http://google.com

# Postal address (add as many lines as necessary)
address:
  - line: New York, New York

# Extra content
extra: '<a href="https://www.lehman.edu/academics/health-human-services-nursing/speech-language-hearing-sciences/">CUNY</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
